version: "3.0"
services:
  test:
    image: tporg951/catpicapi-dev
    container_name: catpicapi-test
    ports:
      - 3000:3000
    volumes:
      - .:/usr/cat-pic-api
      - node_modules:/usr/cat-pic-api/node_modules
    command: "npm run test"
    depends_on:
      - cpa-test-service
  cpa-test-service:
    image: tporg951/catpicapi-test
    container_name: catpicapi-test-db
    volumes:
      - test-db-volume:/usr/cat-pic-api/datastore
volumes:
  node_modules: {}
  test-db-volume: {}
  